name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Replace API key in HTML
      run: |
        sed -i 's/API_KEY_PLACEHOLDER/${{ secrets.GOOGLE_MAPS_API_KEY }}/g' ./path/to/your/index.html

    - name: Print HTML file for debugging
      run: cat ./path/to/your/index.html

    - name: Deploy
      run: |
        echo "Deploying to server"
        # Your deployment commands here
